import LegalLayout from "../components/legal/LegalLayout";

const TermsOfServicePage = () => {
  const sections = [
    {
      id: "acceptance",
      title: "Acceptance of Terms",
      content: (
        <p>
          By creating an account or using Pulse in any way, you agree to be bound by these Terms of
          Service. If you don't agree with any part of these terms, please don't use the platform.
        </p>
      ),
    },
    {
      id: "accounts",
      title: "Your Account",
      content: (
        <>
          <p>
            You're responsible for keeping your login credentials secure and for all activity that
            happens under your account, whether you signed up with an email and password or through
            Google Sign-In.
          </p>
          <p>
            You must provide accurate information when signing up, and you agree not to impersonate
            another person or organization.
          </p>
        </>
      ),
    },
    {
      id: "acceptable-use",
      title: "Acceptable Use",
      content: (
        <>
          <p>You agree not to:</p>
          <ul className="list-disc space-y-1 pl-5">
            <li>Attempt to break out of, abuse, or overload the code execution sandbox</li>
            <li>Submit malicious, harmful, or illegal code through the platform</li>
            <li>Scrape, reverse-engineer, or attempt to extract our problem set in bulk</li>
            <li>Use automated tools to create accounts or spam submissions</li>
            <li>Interfere with other users' access to or use of the platform</li>
          </ul>
        </>
      ),
    },
    {
      id: "code-execution",
      title: "Code Execution & Submissions",
      content: (
        <p>
          Code you write and submit is executed in an isolated, sandboxed environment with strict time
          and memory limits, solely to evaluate your solution against test cases and generate
          AI-powered feedback. Rate limits apply to running and submitting code to keep the platform
          available for everyone.
        </p>
      ),
    },
    {
      id: "ai-feedback",
      title: "AI-Generated Feedback",
      content: (
        <p>
          Feedback on your submissions — including complexity analysis, code quality notes, and
          follow-up questions — is generated by an AI model. It's meant to support your learning, not
          serve as a definitive or professional evaluation, and we don't guarantee its accuracy.
        </p>
      ),
    },
    {
      id: "ip",
      title: "Intellectual Property",
      content: (
        <p>
          Pulse and its original content — including problem descriptions, design, and branding — are
          owned by Pulse and protected by applicable intellectual property laws. The code you write and
          submit remains yours.
        </p>
      ),
    },
    {
      id: "termination",
      title: "Termination",
      content: (
        <p>
          You can delete your account at any time from your profile settings. We may suspend or
          terminate accounts that violate these terms, including abuse of the code execution sandbox or
          disruptive behavior toward the platform or other users.
        </p>
      ),
    },
    {
      id: "disclaimer",
      title: "Disclaimer & Limitation of Liability",
      content: (
        <p>
          Pulse is provided "as is" without warranties of any kind. We aren't liable for any indirect,
          incidental, or consequential damages arising from your use of the platform, including reliance
          on AI-generated feedback for interview preparation.
        </p>
      ),
    },
    {
      id: "changes",
      title: "Changes to These Terms",
      content: (
        <p>
          We may update these Terms of Service from time to time. Continued use of Pulse after changes
          are posted means you accept the updated terms.
        </p>
      ),
    },
    {
      id: "contact",
      title: "Contact",
      content: (
        <p>
          Questions about these terms? Reach out through the contact details on our landing page or your
          account support channel.
        </p>
      ),
    },
  ];

  return (
    <LegalLayout
      title="Terms of Service"
      lastUpdated="August 27, 2026"
      intro="These terms govern your use of Pulse — our AI-powered coding interview practice platform. Please read them carefully."
      sections={sections}
    />
  );
};

export default TermsOfServicePage;